name = "birch_example_10_lazy_evaluation"
version = "0.0.0"
description = "birch example: lazy evaluation for performance"

[dependencies]
birch = { path = "../../" }

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
