name = "gleam_log"
version = "0.1.0"
description = "A modern, production-ready logging library for Gleam"
licences = ["MIT"]
repository = { type = "github", user = "tylerbutler", repo = "gleam_log" }

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gleam_json = ">= 1.0.0 and < 3.0.0"
simplifile = ">= 2.0.0 and < 3.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
