name = "birch_example_03_metadata"
version = "0.0.0"
description = "birch example: structured logging with metadata"

[dependencies]
birch = { path = "../../" }

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
