name = "birch_example_05_console_handler"
version = "0.0.0"
description = "birch example: console handler configuration"

[dependencies]
birch = { path = "../../" }

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
