name = "birch_example_11_error_helpers"
version = "0.0.0"
description = "birch example: error result helpers"

[dependencies]
birch = { path = "../../" }
simplifile = ">= 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
