name = "birch_example_11_error_helpers"
version = "0.0.0"
description = "birch example: error result helpers"

[dependencies]
birch = { path = "../../" }
birl = ">= 1.7.0 and < 2.0.0"
# TODO: Remove constraint after birl update - https://github.com/tylerbutler/birch/issues/32
gleam_stdlib = ">= 0.44.0 and < 0.68.0"
simplifile = ">= 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
