name = "birch_example_15_testing_support"
version = "0.0.0"
description = "birch example: testing support utilities"

[dependencies]
birch = { path = "../../" }
birl = ">= 1.7.0 and < 2.0.0"
# TODO: Remove constraint after birl update - https://github.com/tylerbutler/birch/issues/32
gleam_stdlib = ">= 0.44.0 and < 0.68.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
