name = "birch_example_09_global_config"
version = "0.0.0"
description = "birch example: global configuration"

[dependencies]
birch = { path = "../../" }

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
