name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [erlang, javascript]

    name: Test (${{ matrix.target }})

    steps:
      - uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup
        with:
          node: ${{ matrix.target == 'javascript' }}

      - name: Check formatting
        run: just format-check

      - name: Build
        run: just ${{ matrix.target == 'javascript' && 'build-js' || 'build' }}

      - name: Run tests
        run: just ${{ matrix.target == 'javascript' && 'test-js' || 'test-erlang' }}

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup

      - name: Build docs
        run: just docs
